### PR TITLE
Highlight text after search and add horizontal line under the cursor

### PR DESCRIPTION
**Pull request by jean553**

### CODE REVIEW

**Comment by allan-simon** [comment]
I should try to find a better way for people to inject their own vimrc

**Comment by eliasdorneles** [comment]
> I should try to find a better way for people to inject their own vimrc

that'd be lovely ^^

**Comment by allan-simon** [comment]
especially as now it's no more a vimrc but using neovim :P

**Comment by jean553** [comment]
Yes this issue is outdated. Let's just close it. @allan-simon let you judge if you open a new one for custom neovim conf injection.

**Pull request closed without merging**
